sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/dev/**,**/coverage/**,**/*.cjs,**/*.spec.*,**/*.test.*
sonar.coverage.exclusions=**/*.cjs,**/*.spec.*,**/*.test.*
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info